Harmony
RknB64/Cineflix pull request #21
Opened 2024-05-10 13:04 UTC by th-herve

2024-05-11 18:12 UTC, RknB64 requested changes

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/Controller.php
> +    static protected function render(string $view, array $data = [], bool $withHeaderFooter = true): void
Rajouter string $titre comme suit :
static protected function render(string $titre, string $view, array $data = [], bool $withHeaderFooter = true): void

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/AccueilController.php
> +        $this->render($this->view, $this->data);
$this->render($this->titre, $this->view, $this->data);

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/AjaxRequestController.php
> +                $this->render($this->view, $this->data, false);
$this->render($this->titre, $this->view, $this->data); (pour pas causer d'erreur)

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/CatalogueCinemaController.php
> +        $this->render($this->view, $this->data);
$this->render($this->titre, $this->view, $this->data);

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/DetailFilmController.php
> +        $this->render($this->view, $this->data);
$this->render($this->titre, $this->view, $this->data);

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/InscriptionController.php
> +        $this->render($this->view, $this->data);
$this->render($this->titre, $this->view, $this->data);

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/Page404Controller.php
> +        $this->render($this->view, $this->data);
$this->render($this->titre, $this->view, $this->data);

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/RechercheController.php
> +            $this->render($this->view, $this->data);
$this->render($this->titre, $this->view, $this->data);

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/RechercheController.php
> +        $this->titre    = 'page title';
il y a probablement moyen de mettre un meilleur titre

2024-05-11 18:12 UTC, RknB64 commented on src/controleur/StreamingController.php
> +        $this->render($this->view, $this->data);
$this->render($this->titre, $this->view, $this->data);

2024-05-11 18:12 UTC, RknB64 commented on src/vue/header.php
Remplacer <title>CineFlix</title> l.7 par <title><?= $titre ?></title>

2024-05-11 20:40 UTC, th-herve commented on src/controleur/Controller.php
> +    static protected function render(string $view, array $data = [], bool $withHeaderFooter = true): void
J'ai mis les $titres dans l'array $data. Pour moi c'est une variable utilisée par la vue. Et certaine vue n'utilise pas de titre comme la vue pour autocompléter les villes

2024-05-11 22:20 UTC, RknB64 commented on src/controleur/Controller.php
> +    static protected function render(string $view, array $data = [], bool $withHeaderFooter = true): void
oui je vois. J'ai tenté les modifs dans le mauvais ordre. Voir proposition dans header.php

2024-05-12 14:34 UTC, RknB64 approved these changes

2024-05-12 16:05 UTC, merged